<%
distrib, infos    = ENV.fetch('DISTRIB', 'ubuntu:xenial/16.04').split(':')
codename, version = infos.split('/')
%>
---
driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef_omnibus: false
  
verifier:
  name: inspec
  sudo: true
  patterns:
    - tests/integration/default
  
provisioner:
  name: salt_solo
  log_level: debug
  omnibus_cachier: true
  salt_install: "bootstrap"
  salt_version: "latest"
  salt_minion_id: "kitchen-test-celery"
  
  formula: celery
  pillars-from-files:
    celery.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - celery
  state_top:
    base:
      "*":
        - celery.testing
        - celery.debug        
        - celery.env

        
platforms:
  - name: ubuntu
    image: "ubuntu/xenial"
    platform: "ubuntu"
    driver_config:
      run_command: /lib/systemd/systemd
      pid_one_command: /lib/systemd/systemd      
      provision_command:
        - apt-get update && apt-get install -y locales
        - echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
        - locale-gen en_US.UTF-8      

suites:
  - name: default
    driver_config:
      hostname: celery-default.ci.local

  - name: worker
    driver_config:
      hostname: celery-worker.ci.local
    verifier:
      patterns:
        - tests/integration/default/
        - tests/integration/worker/
    provisioner:
      state_top:
        base:
          '*':
            - celery.testing
            - celery.debug            
            - celery.worker

  - name: flower
    verifier:
      patterns:
        - tests/integration/default/
        - tests/integration/flower/
    driver_config:
      hostname: celery-flower.ci.local
    provisioner:
      state_top:
        base:
          '*':
            - celery.testing
            - celery.debug            
            - celery.flower
            
