---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: celery
  pillars-from-files:
    celery.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - celery
  state_top:
    base:
      "*":
        - celery.testing
        - celery
        - celery.worker
        - celery.debug 
platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
suites:
  - name: default
