---
driver:
  name: vagrant
  cachier: true
  require_chef_omnibus: latest
  customize:
    memory: 2048

verifier:
  name: inspec
  sudo: true
  patterns:
    - tests/integration/default
  
provisioner:
  name: salt_solo
  log_level: debug
  omnibus_cachier: true
  salt_install: "bootstrap"
  salt_version: "latest"
  salt_minion_id: "kitchen-test-celery"
  
  formula: celery
  pillars-from-files:
    celery.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - celery
  state_top:
    base:
      "*":
        - celery.testing
        - celery.debug        
        - celery.env

        
platforms:
  # - name: centos
  #   driver:
  #     box: bento/centos-7.4
  - name: ubuntu
    driver:
      box: bento/ubuntu-16.04

suites:
  - name: default

  - name: worker
    verifier:
      patterns:
        - tests/integration/default/
        - tests/integration/worker/
    provisioner:
      state_top:
        base:
          '*':
            - celery.testing
            - celery.debug            
            - celery.worker

  - name: flower
    verifier:
      patterns:
        - tests/integration/default/
        - tests/integration/flower/
    provisioner:
      state_top:
        base:
          '*':
            - celery.testing
            - celery.debug            
            - celery.flower
            
