---
driver:
  name: docker
  privileged: true

verifier:
  name: inspec
  sudo: true
  patterns:
    - tests/integration/default
  
# provisioner:
#   name: salt_solo
#   log_level: debug
#   omnibus_cachier: true
#   salt_install: "bootstrap"
#   salt_version: "latest"
#   salt_minion_id: "kitchen-test-celery"
  
#   formula: celery
#   pillars-from-files:
#     celery.sls: pillar.example
#   pillars:
#     top.sls:
#       base:
#         "*":
#           - celery
#   state_top:
#     base:
#       "*":
#         - celery.testing
#         - celery.debug        
#         - celery.env

        
platforms:
  - name: ubuntu-17.04

suites:
  - name: default
